name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  PYTHON_VERSION: "3.14"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"

      - name: "Resolve Project Dependencies Using Pip"
        run: |
          python -m pip install --upgrade pip
          pip install -r functions/requirements.txt
          pip install -r requirements-dev.txt

      - name: "Run tests"
        run: pytest
